export const C = {
  bg: "#1B2420",
  panel: "#232D27",
  panelAlt: "#2B352E",
  border: "#34403A",
  cream: "#F2E8D5",
  muted: "#A9B3A8",
  dim: "#7C9473",
  orange: "#E2793A",
  green: "#7C9473",
  gold: "#D9A441",
  terra: "#C1502E",
};

export const WHEEL_COLORS = [
  "#E2793A", "#7C9473", "#D9A441", "#C1502E",
  "#8A9A5B", "#4F6B5A", "#B5651D", "#5B7065",
];

export const SANS = "'Work Sans', sans-serif";
export const SERIF = "'Fraunces', serif";

export const s = {
  page: {
    minHeight: "100vh",
    background: C.bg,
    display: "flex",
    justifyContent: "center",
    padding: "24px 16px 64px",
    fontFamily: SANS,
  },
  container: {
    width: "100%",
    maxWidth: "480px",
    display: "flex",
    flexDirection: "column",
    gap: "22px",
  },
  header: { textAlign: "center", display: "flex", flexDirection: "column", gap: "4px" },
  eyebrow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    color: C.gold,
    fontSize: "12px",
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    fontWeight: 600,
  },
  title: {
    fontFamily: SERIF,
    fontWeight: 700,
    fontSize: "34px",
    color: C.cream,
    margin: 0,
    letterSpacing: "-0.01em",
  },
  subtitle: { color: C.muted, fontSize: "13.5px", margin: 0 },
  syncWarning: { color: C.terra, fontSize: "12px", margin: "4px 0 0" },
  tabBar: {
    display: "flex",
    background: C.panel,
    border: `1px solid ${C.border}`,
    borderRadius: "999px",
    padding: "4px",
    gap: "2px",
  },
  tab: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    background: "transparent",
    border: "none",
    borderRadius: "999px",
    padding: "9px 2px",
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: "12px",
    color: C.muted,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "background 0.15s ease, color 0.15s ease",
  },
  tabActive: { background: C.orange, color: C.bg },
  tabBadge: {
    background: C.bg,
    color: C.cream,
    borderRadius: "999px",
    fontSize: "10.5px",
    fontWeight: 700,
    padding: "1px 6px",
    marginLeft: "2px",
  },
  panel: {
    background: C.panel,
    border: `1px solid ${C.border}`,
    borderRadius: "18px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "14px",
  },
  sectionTitle: { fontFamily: SERIF, fontWeight: 700, fontSize: "19px", color: C.cream, margin: 0 },
  input: {
    flex: 1,
    minWidth: 0,
    background: C.bg,
    border: `1px solid ${C.border}`,
    borderRadius: "10px",
    padding: "10px 12px",
    color: C.cream,
    fontSize: "14px",
    fontFamily: SANS,
  },
  textarea: {
    background: C.bg,
    border: `1px solid ${C.border}`,
    borderRadius: "10px",
    padding: "10px 12px",
    color: C.cream,
    fontSize: "14px",
    fontFamily: SANS,
    lineHeight: 1.5,
    minHeight: "120px",
    resize: "vertical",
    width: "100%",
  },
  btnPrimary: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    background: C.orange,
    color: C.bg,
    border: "none",
    borderRadius: "999px",
    padding: "12px 24px",
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: "14.5px",
    cursor: "pointer",
  },
  btnGreen: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    background: C.green,
    color: C.bg,
    border: "none",
    borderRadius: "10px",
    padding: "10px 16px",
    fontFamily: SANS,
    fontWeight: 600,
    fontSize: "13px",
    whiteSpace: "nowrap",
    cursor: "pointer",
  },
  btnGhost: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    background: "transparent",
    color: C.muted,
    border: `1px solid ${C.border}`,
    borderRadius: "999px",
    padding: "8px 14px",
    fontFamily: SANS,
    fontWeight: 500,
    fontSize: "13px",
    cursor: "pointer",
  },
  iconBtn: {
    background: "transparent",
    border: "none",
    color: C.muted,
    display: "flex",
    alignItems: "center",
    padding: "5px",
    borderRadius: "50%",
    cursor: "pointer",
  },
  muted: { color: C.muted, fontSize: "13px", margin: 0 },
  empty: { color: C.dim, fontSize: "13.5px", margin: 0, textAlign: "center", padding: "10px 0" },
};
